dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

env:
  global:
  - NJOBS=3
  - COQ_VER="8.8.0"

notifications:
  email:
  - false

install:
- export OPAMROOT=$HOME/.opam
- opam init -j ${NJOBS}  -n -y
- eval $(opam config env)
- opam repo add coq-released http://coq.inria.fr/opam/released || echo "coq-released registered"
- opam install coq.${COQ_VER} -y
- opam install coq-bignums -y

script:
 - ./configure.sh
 - make -j ${NJOBS}
 - make install

